# Generated by Django 5.0.3 on 2024-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Date_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
