# Generated by Django 5.0.3 on 2024-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Feedback', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
