# Generated by Django 5.0.3 on 2024-03-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonials_sub_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
