# Generated by Django 5.0.3 on 2024-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_testimonials_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=15, null=True)),
                ('Resume', models.FileField(null=True, upload_to='resumes/')),
            ],
        ),
    ]
