# Generated by Django 5.0.3 on 2024-03-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=15, null=True)),
                ('Resume', models.FileField(null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Password', models.CharField(max_length=16, null=True)),
                ('Access', models.BooleanField(default=False)),
                ('OTP', models.CharField(max_length=6, null=True)),
                ('Token', models.CharField(max_length=250, null=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField(max_length=2000, null=True)),
                ('Requirments', models.CharField(max_length=1000, null=True)),
                ('Salary_Range', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='applications',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs'),
        ),
    ]
