# Generated by Django 5.0.3 on 2024-03-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_role_remove_employee_access_remove_employee_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='OTP',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
