# Generated by Django 5.0.3 on 2024-03-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employee_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Viewed'), ('F', 'Follow Up'), ('FF', 'Followed Up')], default='P', max_length=2),
        ),
    ]
