# Generated by Django 5.0.3 on 2024-04-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Date_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
